# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  # base_url: http://subdomain.domain.com
  # server_port: 8123
  # For extra security set this to only accept connections on localhost if NGINX is on the same machine
  # Uncommenting this will mean that you can only reach Home Assistant using the proxy, not directly via IP from other clients.
  # server_host: 127.0.0.1
  use_x_forwarded_for: true
  # You must set the trusted proxy IP address so that Home Assistant will properly accept connections
  # Set this to your NGINX machine IP, or localhost if hosted on the same machine.
  trusted_proxies:
    - 0.0.0.0/0
    # Other things I tried
    # - 127.0.0.1
    # - 172.19.0.0/16
    # - 172.19.0.0/24
    # - 172.19.0.3/16
    # - 172.19.0.3/24
    # - 192.168.0.0/24
    # - 192.168.1.0/24
    # - nginx_nginx_1
  ip_ban_enabled: true
  login_attempts_threshold: 5