version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /docker/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /dev/serial/by-id/:/dev/serial/by-id #usb devices
    devices:
      - /dev/zigbee:/dev/ttyUSB0      
    restart: unless-stopped
    privileged: true    
    networks:
      - npm-network
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=America/Argentina/Buenos_Aires 
    volumes:
      - /docker/nodered/data:/data
    networks:
      - npm-network
networks:
  npm-network:
    external: true