version: '3.3'

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - 9443:9443
    volumes:
      - ./volumes/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always  