version: '3'
services:  
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - /docker/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=America/Argentina/Buenos_Aires
    devices:
      # Make sure this matched your adapter location
      - /dev/zigbee:/dev/ttyUSB0
    networks:
      - npm-network

  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto
    #ports:
    #  - "1883:1883"
    #  - "9001:9001"
    volumes:
      - /docker/mosquitto/config:/mosquitto/config
      - /docker/mosquitto/logs:/mosquitto/log
      - /docker/mosquitto/data:/mosquitto/data
    restart: always
    environment:
      - TZ=Europe/Madrid
    networks:
      - npm-network

networks:
  npm-network:
    external: true